name: Deploy to NPM on release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish_npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace NPM name
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "\"vis-timeline\""
          replace: "\"@vizlib/vis-timeline\""
          include: "package.json"
      - name: Replace NPM version
        run: |
          npm --no-git-tag-version version ${GITHUB_REF##*/}
      - name: Build & publish
        run: |
          cat package.json
